### ISSUE TITLE
Requirements/Instructions to run a simple buildfarm ?

### ISSUE THREAD

**Issue by asmodehn** [ros-infrastructure/ros_buildfarm#102] opened 2015-09-25 03:43 UTC
From the doc I could gather that to setup a ROS build farm, I need to - after gross simplification - : 
- deploy a lot of machines ( virtual or not ) https://github.com/ros-infrastructure/buildfarm_deployment
- setup these with a lot of configuration ( ) https://github.com/ros-infrastructure/buildfarm_deployment_config
- deploy a lot of software ( python, jenkins, ros, etc. ) https://github.com/ros-infrastructure/ros_buildfarm
- setup a lot of configuration ( ssh kays, gpg keys, credentials, url, etc. ) https://github.com/ros-infrastructure/ros_buildfarm_config

When someone wants to setup Continuous Integration for their software, I feel this is overkill. Personally, when working on a software (non ROS), to setup Continuous integration, I usually do : 
- Build the software out of Repository clone with a script.
- Test the software out of the build step with a script and package it.
- Install Jenkins on an idle machine somewhere to automatize the checkout and the scripts run.
- If jenkins has plugins to do fancy things (display test result, publishing packages), I can set them up.
- If I ever need to compile for multiple platform I setup one slave per platform target.
- If I ever need to cross compile, I setup custom slaves for that too ( with fancy cmake scripts ).
And thats it.

This might be a bit naive, but I doubt it should require more than these few steps to empower ros developers and allow them to run their own build farm for their own packages. And I think there are two fundamentally different problems that seem to get entangled here : continuous integration and  cloud setup. I feel many software developer now understand the importance of the first one and realize they should do it themselves, while delegating the second one ( to a different team or even another company )

I think ros_buildfarm should be usable without knowing/caring about buildfarm_deployment
=> Is that possible ?
=> Is it currently a goal for ros_buildfarm ?
=> If it is, please let me know where I should be able to find the list of requirements for ros_buildfarm. That would leave me the choice of _how_ I go about satisfying these requirements (docker or not, multiple machines or not, etc.)

I have been trying to setup a buildfarm of one machine for a test ( and to get the configuration right as a first step ), but I have been unsuccessful so far. So hopefully I can help a bit with documentation in order to make it easier for others...

**Comment by tfoote** [comment] 2015-09-25 05:17
The design of this system is to be able to replace the entire buildfarm that OSRF runs to produce one or more rosdistros. It configures CI for the whole rosdistro, it performs the autodocumentation of all packages, it builds the debians and rebuilds them automatically when they're released and uploads them into a repository. 

It is not designed for individual developers to run for their individual packages. We expect most individual developers to submit their packages to be indexed on the public buildfarm.

The other expected user is a company building a product on ROS that needs to have full control of the packages which they build and deploy and/or have a set of proprietary packages that they do not want to release but want to build packages in addition to the publicly released packages. Such that they are either forking or extending the rosdistro. It's a lot of work to maintain a rosdistro but there are instances where it makes sense to do so. 

For the individual developer we have instructions how to reproduce the individual jobs: [prerelease](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/prerelease_jobs.rst) [doc](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/doc_jobs.rst#run-the-doc-job-locally) [devel](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/devel_jobs.rst#run-the-devel-job-locally) [release](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/jobs/release_jobs.rst#run-the-release-job-locally)

If you want to set up your own CI for a couple packages I'd recommend you simply use the local devel job in your custom script and do as you've suggested above. That approach does not scale to 1500 packages across 4+ architectures which is what the majority of the infrastructure here is dealing with.

If you'd like to discuss more about how to use the ros_buildfarm I suggest you join the [ros-sig-buildfarm](https://groups.google.com/d/forum/ros-sig-buildfarm)

**Comment by asmodehn** [comment] 2015-09-25 05:46
Thank you for the detailed explanation of these use cases. 
I am already on that mailing list.

I am actually in the case of a company ( with @stonier ) trying to build a set of proprietary packages, while still using the usual public packages.
We do not plan to fork a rosdistro ( as in _modifying_ existing packages ), but only to extend it ( as in _add_ more ), and we have very limited resources ( actually me for a few days only ) to allocate to setting up that continuous integration. So the ideal case for us would be to be able to replicate a "standard build process" while being able to customize what to build (or not).

I m now trying ros_buildfarm to find out which way ( [ros_buildfarm](https://github.com/ros-infrastructure/ros_buildfarm) / [buildbot-ros](https://github.com/mikeferguson/buildbot-ros) / custom jenkins jobs ) is the best way to go for us... 
I ll definitely check these instructions to reproduce the individual jobs, thanks.

Anyway I ll continue the conversation by email then :)

**Comment by dirk-thomas** [comment] 2015-09-25 16:48
The following ticket in the buidlfarm_deployment repo deals is about deploying the whole infrastructure on a single machine: https://github.com/ros-infrastructure/buildfarm_deployment/issues/42

If this would be addressed it should be easy for you do deploy all necessary services on a single machine / VM.

Since the setup of Jenkins, docker and the webserver is not trivial we have automated that process. If you want to manually do that you might need to read the configuration encoded in puppet scripts etc. and perform them manually.

**Comment by tfoote** [comment] 2015-09-28 06:11
I also added a design over view at: http://wiki.ros.org/buildfarm/Design

**Comment by tfoote** [comment] 2016-01-11 21:56
We've designed the system to be module and enable reuse of any of the parts (such as running the jobs standalone) which can be reused in places like travis if you just want a simple script to test with. In general though this is not a use case we're planning to focus on. 

With the documentation above and the longer term enhancement to support all in one deployments https://github.com/ros-infrastructure/buildfarm_deployment/issues/42, I'm going to close this issue.

**Closed by tfoote** 2016-01-11 21:56 UTC

**Comment by jinhkim** [comment] 2018-08-21 22:14
Any update on this issue?
I'm also looking into implementing CI but for a forked version of ROS. I'm seeking a way to do this with a single machine but failing that, will the buildfarm approach work with a single machine and multiple internet-connected VMs?

**Comment by dirk-thomas** [comment] 2018-08-21 22:33
> Any update on this issue?

This issue has been closed 2.5 yrs ago so there is nothing actively being done atm. The referenced ticket specific to the machine provisioning doesn't have any update and is a prerequisite for the `ros_buildfarm` to be deployed on a single machine.
