### ISSUE TITLE
Development jobs using hg are triggered way too often

### ISSUE THREAD

**Issue by kmhallen** [ros-infrastructure/ros_buildfarm#488] opened 2017-12-01 15:38 UTC
It looks like development jobs for repositories using hg are triggered all the time, even when there are no commits. Repositories using git are not affected, only hg.

http://build.ros.org/job/Idev__multisense_ros__ubuntu_trusty_amd64/
http://build.ros.org/job/Idev__rbdl__ubuntu_trusty_amd64/
http://build.ros.org/job/Idev__oxford_gps_eth__ubuntu_trusty_amd64/
http://build.ros.org/job/Kdev__oxford_gps_eth__ubuntu_xenial_amd64/
http://build.ros.org/job/Idev__ueye__ubuntu_trusty_amd64/
http://build.ros.org/job/Kdev__ueye__ubuntu_xenial_amd64/

**Comment by tfoote** [comment] 2017-12-01 19:10
Based on timing I believe that these are getting retriggered because when our agents get cycled out the workspace disappears. 

This used to be an issue https://issues.jenkins-ci.org/browse/JENKINS-12404 but it's stated that it's resolved by turning on "cashing". Maybe there's been a regression since we resolved this in #206 and https://github.com/ros-infrastructure/buildfarm_deployment/pull/117 ?

**Comment by nuclearsandwich** [comment] 2017-12-01 19:45
Everything on the buildfarm currently matches the configurations in the PRs @tfoote mentioned. I do find it interesting that in the job configuration `(Default)` is used but in the glocal config it's `Default` without parentheses. But that's presumably what was working previously.

**Closed** 2017-12-19 06:36 UTC
