### ISSUE TITLE
Add check for dependencies before trying to build packages

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#61] opened 2015-04-26 10:03 UTC
We currently fail in the middle of the build if a required binary package is missing from the repository. This could be detected before attempting the build and error on with a useful message. 

We have a script for this purpose on the old buildfarm. 

https://github.com/ros-infrastructure/buildfarm/blob/master/scripts/assert_package_dependencies_present.py

Adding this functionality will improve the user experience by providing a shorter traceback and can state cleanly that there's missing dependencies instead of just having apt fail. 

This comes from: http://54.183.26.131:8080/job/Jbin_uT64__turtle_tf__ubuntu_trusty_amd64__binary/1/ and is more asthetic in nature. 

It is the result of a failure of the buildfarm infrastructure. #45 We could consider making this dependency check abort instead of fail so as not to send an email, since it should not happen if things are running correctly. The other common case where this might happen is an added dependency before a reconfigure of the farm has happened for Jenkins dependencies to match the regular ones.

**Comment by dirk-thomas** [comment] 2015-04-26 17:31
I don't think the referenced script would help in this case. It is being invoked with the package name to be built and fetches the sourcedeb of it. Then it extracts the direct build dependencies and ensures that they are present in the apt repo.

The current job already ensures that all direct dependencies are "green" (https://github.com/ros-infrastructure/ros_buildfarm/blob/1e48893dee11410cfd67c1b7b2d573a1c3790de5/ros_buildfarm/templates/release/binarydeb_job.xml.em#L58). And looking at the job output it is not a direct dependency which is missing but something several levels upstream:

    Investigating (0) ros-jade-rosconsole [ amd64 ] < none -> 1.11.11-0trusty-20150422-125146-0700 > ( misc )
    Broken ros-jade-rosconsole:amd64 Depends on ros-jade-rosbuild [ amd64 ] < none -> 1.12.1-0trusty-20150422-120306-0700 > ( misc )
      Considering ros-jade-rosbuild:amd64 1 as a solution to ros-jade-rosconsole:amd64 -1
      Holding Back ros-jade-rosconsole:amd64 rather than change ros-jade-rosbuild:amd64
    Investigating (1) ros-jade-roscpp [ amd64 ] < none -> 1.11.11-0trusty-20150422-125753-0700 > ( misc )
    Broken ros-jade-roscpp:amd64 Depends on ros-jade-rosconsole [ amd64 ] < none -> 1.11.11-0trusty-20150422-125146-0700 > ( misc )
      Considering ros-jade-rosconsole:amd64 -1 as a solution to ros-jade-roscpp:amd64 9998
        Reinst Failed early because of ros-jade-message-generation:amd64
        Reinst Failed because of ros-jade-rosbuild:amd64

The direct upstream dependency of the failing job is `roscpp`.

**Comment by tfoote** [comment] 2015-04-26 18:07
Yes the current script cannot be dropped in as is. I expect we would rework it into something that runs in docker isolation. I only linked to that script for reference since it has been useful and provides the similar functionality on the old farm. 

You're right it would be better to test recursive dependencies, even better would be to verify that the the packages are considered installable. 

Green and present are not necessarily the same. If the dependency has been invalidated it can still be green but missing on the farm. In steady state this shouldn't happen, but i've seen this check prevent a lot of build when things get released during an active build. This script stops the downstream builds quickly instead of letting them start bootstrapping only to find out that a dependency has been pulled out from under them.

**Comment by dirk-thomas** [comment] 2015-04-26 18:10
The problem is not a difference between "green" and "present" of the direct dependencies. Please wait for the full analysis which I will post soon.

**Comment by dirk-thomas** [comment] 2015-04-26 18:13
We should first figure out what actually happened, fully understand the scenario and then consider fixes / workarounds. Looking through the job history the following happened based on facts:

* `turtle_tf` trusty amd64 #1 (http://54.183.26.131:8080/job/Jsrc_uT__turtle_tf__ubuntu_trusty__source/1/) was triggered at Apr 25, 2015 2:45 AM by its upstream source job

* the source build number was also #1 since it was just released (http://54.183.26.131:8080/job/Jsrc_uT__turtle_tf__ubuntu_trusty__source/)

* the first "bug" you can see there is that the source job on trusty was triggered by the `Jrel_arm_trigger-jobs` build #7105 (http://54.183.26.131:8080/job/Jrel_arm_trigger-jobs/). While this is something which needs fixing the job would have been triggered anyway by the non-arm trigger jobs job...

* at the time when the `turtle_tf` binary job was started all direct upstream dependencies where "green"

* the wave of Jade builds had passed `roscpp` etc. at that time long ago. Most of the Debian packages had a date 22nd / 23rd of April

* then a new release of `geneus` was merged: https://github.com/ros/rosdistro/commit/b99625741780edc28563d5867b132eae9e9a23a0

* the first build of `geneus` failed due to docker memory issues (http://54.183.26.131:8080/job/Jbin_uT64__geneus__ubuntu_trusty_amd64__binary/8/console) at Apr 24, 2015 8:43 AM

* it got retriggered a bit later: Apr 24, 2015 11:03 PM (http://54.183.26.131:8080/job/Jbin_uT64__geneus__ubuntu_trusty_amd64__binary/9/) and built the version 2.2.1 successfully

* the new `geneus` Debian package is being imported in the apt repo: http://54.183.26.131:8080/job/Jrel_import-package/12090/console this invalidates the packages directly depending on it: `message_generation` and `roseus`. This seems to be the second bug - we want to invalidate downstream packages recursively which hasn't been implemented yet: https://github.com/ros-infrastructure/reprepro-updater/issues/2

* `message_generation` #7 fails to build shortly afterwards at Apr 24, 2015 11:10 PM (thank you Docker): http://54.183.26.131:8080/job/Jbin_uT64__message_generation__ubuntu_trusty_amd64__binary/7/

* the retriggered job has to wait in the queue for a while and #8 gets build successfully at Apr 25, 2015 9:01 AM which is after the `turtle_tf` job has failed.

Based on the traceable history of events I conclude that the `turtle_tf` job failes because a new "wave" was started while an old "wave" was still going. The new wave invalidates a certain Debian package which is then not installable by job of the "old" wave.

Therefore I would recommend to extend the groovy script (https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/templates/snippet/builder_system-groovy_verify-upstream.xml.em) to check the state of all **recursive** upstream jobs instead of only the direct upstream jobs.

**Comment by tfoote** [comment] 2015-04-27 21:28
I agree we should extend the groovy script to find the recursive dependencies, subject to our ABI compatibility settings. 

But I think that should be done in addition to this check. The actual precondition for the build is that all debian package dependencies are available and installable. Testing this will prevent the somewhat cryptic errors for missing dependencies as well as saving a lot of time building since we can test for installability without actually running the installation. It will alos catch both missing ROS packages as well as potentially missing other dependencies. If everything goes well it should never hit, but we know that things don't always go perfectly and providing this test of the precise prerequisites is valuable toward that end.

**Comment by dirk-thomas** [comment] 2015-04-27 23:26
Since the case is not supposed to happen I would rather not reintroduce the apt repo check. Simply because we have to maintain it and also port the same check to new platforms like Fedora. It would also shadow problems we are not aware of if the not-supposed-to-happen-case does happen.

I will create a patch for the Groovy script to check recursive upstream jobs. @tfoote Can you please take care of the long standing reprepro-updtaer ticket?

**Comment by dirk-thomas** [comment] 2015-04-29 00:22
I have implemented the recursive upstream project checking in PR #63.

**Comment by dirk-thomas** [comment] 2015-05-30 19:58
Since the last remaining item from the above list is ticketed separately I will close this ticket.

@tfoote Please address ros-infrastructure/reprepro-updater#2

**Closed by dirk-thomas** 2015-05-30 19:58 UTC
Labels: enhancement
