### ISSUE TITLE
Devel jobs rosdep not handling conditional attributes

### ISSUE THREAD

**Issue by ross-desmond** [ros-infrastructure/ros_buildfarm#625] opened 2019-05-01 18:03 UTC
Jenkins finds all dependencies in package xml regardless of conditionals.

Example build: http://build.ros.org/job/Kdev__aws_common__ubuntu_xenial_amd64/16/console
Failure occurs due to this change (additional of ROS version 2 conditional): https://github.com/aws-robotics/utils-common/commit/756b8bf89006500700828bdf88e7da12f12cbedd

Conditionals defined in package version 3: http://www.ros.org/reps/rep-0149.html

Jenkins log:
```
16:31:53 Identified the following run and test dependencies (ignoring packages available from source):
16:31:53   - ament_cmake_gmock <-- (should not have been found due to conditional)
16:31:53   - ament_cmake_gtest <-- (should not have been found due to conditional)
16:31:53   - curl
16:31:53   - google-mock
16:31:53   - gtest
16:31:53   - libssl-dev
16:31:53   - uuid
16:31:53   - zlib
```

**Comment by dirk-thomas** [comment] 2019-05-01 18:14
This looks like a duplicate of #620.

The last failing build of the referenced job was on Apr 4 which was before the patch from #621 had been merged. I just triggered a new build of the referenced job which has already passed the point where it failed before.

**Closed by dirk-thomas** 2019-05-01 18:14 UTC
Labels: duplicate

**Comment by ross-desmond** [comment] 2019-05-01 18:15
Lightning fast, thank you for handling this!
