### ISSUE TITLE
registry connection failure we could catch and abort instead of fail

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#111] opened 2015-10-18 01:00 UTC
http://54.183.26.131:8080/job/Jbin_uT64__eigen_typekit__ubuntu_trusty_amd64__binary/2/console

```
# BEGIN SECTION: Build Dockerfile - binarydeb task
00:00:06.001 + cd /home/jenkins-slave/workspace/Jbin_uT64__eigen_typekit__ubuntu_trusty_amd64__binary/docker_generating_docker
00:00:06.001 + python3 -u /home/jenkins-slave/workspace/Jbin_uT64__eigen_typekit__ubuntu_trusty_amd64__binary/ros_buildfarm/scripts/misc/docker_pull_baseimage.py
00:00:06.001 Get base image name from Dockerfile 'Dockerfile': ubuntu:trusty
00:00:06.001 Check docker base image for updates: docker pull ubuntu:trusty
00:00:06.328 Pulling repository ubuntu
00:00:06.669 time="2015-10-17T21:35:01Z" level=fatal msg="Get https://index.docker.io/v1/repositories/library/ubuntu/images: net/http: transport closed before response was received" 
00:00:06.679 Build step 'Execute shell' marked build as failure
00:00:06.681 [ssh-agent] Stopped.
00:00:06.724 [description-setter] Could not determine description.
00:00:06.730 Sending e-mails to: ros-buildfarm-jade@googlegroups.com william+buildfarm@osrfoundation.org
00:00:07.977 Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
```

**Comment by dirk-thomas** [comment] 2016-01-27 01:03
Duplicate of #119.

**Closed by dirk-thomas** 2016-01-27 01:03 UTC
Labels: enhancement
