### ISSUE TITLE
Add HAROS static analysis output

### ISSUE THREAD

**Issue by nlimpert** [ros-infrastructure/ros_buildfarm#596] opened 2018-12-19 11:07 UTC
In addition to #541 our next goal is to add support for the static analysis framework called `HAROS` (see [this repo](https://github.com/git-afsantos/haros) and [this general demo](https://git-afsantos.github.io/haros/#dashboard) - the demo shows a generated HTML visualizing the analysis of the `haros_tutorials` package) to `roswiki` pages. In particular we started enhancing the scripts of the `devel_jobs` in a fork of this repo (see [this branch](https://github.com/nlimpert/ros_buildfarm/tree/nlimpert/haros) as a working prototype).

As of now this approach results in an extension of the `build_and_test` Dockerfile to execute the analyse functionality of `HAROS`.
The `json`-output of `HAROS` is currently placed in the folder `ws/haros/result`.

Currently we are in the process of deciding where the execution of `HAROS` should take place. We currently see the following options to realise this, which we would like to discuss in this issue:

1. Add `HAROS` execution as an addition to one of the Docker images running in the existing `devel`-jobs. Note that this is the current realisation as seen in the branch in our [fork](https://github.com/nlimpert/ros_buildfarm/commit/7bc2d751898883eb8b92e48b80e19fdc77e056e8). The benefit would be that this would result in a minimal overhead to the already existing `build_and_test` Docker image and in turn minimize additional load on the buildfarm. However this adds another feature to an existing functionality which might not take place there.

2. Add another Dockerfile generated by running the `docker_generating_dockers` Dockerfile in the `devel_jobs` to execute `HAROS`. This would allow to isolate running the QA process in general and thus allow to combine the approach with additional QA processing frameworks. In turn this would add more load to the buildfarm as it would require running an additional Docker container.

So we would like to start a discussion either which approach is of desire or of another idea that we can implement in how to achieve the desired functionality.

**Comment by nlimpert** [comment] 2018-12-19 11:10
@gavanderhoorn @itualami @droter fyi

**Comment by gavanderhoorn** [comment] 2018-12-19 11:30
> In addition to #541 our next goal is to add support for the static analysis framework called `HAROS` [..]

I believe we're currently looking at HAROS as it already nicely integrates a nr of other static analysis tools, but nothing is set in stone at this point.

It would be nice if we could discuss possible integrations of static analysis tools in general -- especially where those would fit in the overall workflow / setup of a buildfarm, as @nlimpert writes.

Also: would this be something that connects to #590?

**Comment by tfoote** [comment] 2018-12-20 20:00
This looks to have moderately low overhead for the installation and as long as it doesn't have a significant add to the devel job's running time, merging this into the main devel jobs makes sense. How do reports come out of it? The other option for this might be to integrate it like we have done for linters with automatically generated unit tests, such that they can be another unit test for each package that users would also be able to reproduce in their workspace.

**Comment by max-krichenbauer** [comment] 2019-08-28 04:56
Sorry if the conversation has already moves somewhere else.
I'm curious about the current status of this project.

I've been successful in applying this approach:
https://github.com/nlimpert/ros_buildfarm/commit/7bc2d751898883eb8b92e48b80e19fdc77e056e8

and added a parser so the result of HAROS is displayed in Jenkins:
https://github.com/max-krichenbauer/ros_buildfarm/commit/3720013b265b9bf408ce21779db989a933fd8893

But I think the main goal of people was to incorporate the result in the Wiki, is that correct?

**Comment by nlimpert** [comment] 2019-08-28 11:52
> I've been successful in applying this approach:
> [nlimpert@7bc2d75](https://github.com/nlimpert/ros_buildfarm/commit/7bc2d751898883eb8b92e48b80e19fdc77e056e8)

:+1: but I guess the approach is outdated by now in terms of the effort in [`haros_catkin`](https://github.com/rosin-project/haros_catkin).

[nlimpert@7bc2d75](https://github.com/nlimpert/ros_buildfarm/commit/7bc2d751898883eb8b92e48b80e19fdc77e056e8) installs HAROS manually (see [install_haros.Dockerfile.em](https://github.com/nlimpert/ros_buildfarm/blob/b98fbef968f9eeba2822153860632af4d0d5a272/ros_buildfarm/templates/snippet/install_haros.Dockerfile.em)). However, `haros_catkin` installs haros and required dependencies in a [`catkin_virtualenv`](https://github.com/locusrobotics/catkin_virtualenv) which in turn is a Python virtualenv.

An effort in `haros_catkin` is to allow running it as a test dependency (see [this PR](https://github.com/rosin-project/haros_catkin/pull/16)) which in turn might not require modifications on the buildfarm. In the end I'd consider [nlimpert@7bc2d75](https://github.com/nlimpert/ros_buildfarm/commit/7bc2d751898883eb8b92e48b80e19fdc77e056e8) to be unnecessary.

> 
> and added a parser so the result of HAROS is displayed in Jenkins:
> [max-krichenbauer@3720013](https://github.com/max-krichenbauer/ros_buildfarm/commit/3720013b265b9bf408ce21779db989a933fd8893)
> 
> But I think the main goal of people was to incorporate the result in the Wiki, is that correct?

Yes, that was the main purpose but I guess we can discuss whether it makes sense to integrate this into Jenkins directly - I actually like the idea as it would nicely integrate the HAROS output for each particular job executed on the buildfarm.

**Comment by max-krichenbauer** [comment] 2019-08-29 04:23
Thank you for your message!
I understand that nlimpert@7bc2d75 is no longer the approach you're going for, since whether or not HAROS can and should be used depends on the package.
I used it for my studies and experiments because I'm not developing any packages, so I wanted to "force it" onto the existing ROS packages.
The new approach of course makes much more sense.

However, I think it could be useful to offer both displaying the HAROS result in the wiki as well as in Jenkins. If there is interest I could prepare a cleaned-up PR.

I don't understand yet how the wiki works - the github page about it isn't extensively well documented. Any information on this topic would be very welcome.

**Comment by nlimpert** [comment] 2019-08-29 08:18
> However, I think it could be useful to offer both displaying the HAROS result in the wiki as well as in Jenkins. If there is interest I could prepare a cleaned-up PR.

Sounds very interesting. But we might discuss this in a bigger round either here or within next week's telco with @gavanderhoorn @itualami @droter. I'll ask @itualami to invite you.

> 
> I don't understand yet how the wiki works - the github page about it isn't extensively well documented. Any information on this topic would be very welcome.

Not a proper step-by-step walkthrough but:
There's a vagrant setup available to test the ROS Wiki scripts and the general functionality found [here](https://github.com/ros-infrastructure/roswiki_vagrant). Note that there's a fork of this repo available [here](https://github.com/nlimpert/roswiki_vagrant) which should work as described in the README. This helped me to understand most of its functionality.
Feel free to contact me if you have trouble regarding this repo (or maybe file an issue).

**Comment by max-krichenbauer** [comment] 2019-08-30 05:35
Thank you!

I managed to set up a wiki from https://github.com/ros-infrastructure/roswiki without Vagrant, but I struggle to understand how the buildfarm data about test results ends up there.
It seems like the package can enable exporting the test results by setting `collate_test_stats` ( https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/templates/devel/devel_job.xml.em#L263 ), which will then be written to `collated_test_stats/results.yaml`.
But when the wiki is building the badges it will try to find this data in the packages' manifest.yaml ( https://github.com/ros-infrastructure/roswiki/blob/master/macro/headers.py#L186 )

I guess I'm missing an alternative route or either of the repositories is not up-to-date.

I think @itualami already invited me to the telco next week - looking forward to listening in and hopefully gain some understanding.

Sorry I keep bothering people - hopefully I can make it up soon with some actual contributions.

**Comment by dirk-thomas** [comment] 2020-10-14 17:26
Closing due to age / activity.

**Closed by dirk-thomas** 2020-10-14 17:26 UTC
Labels: enhancement
