### ISSUE TITLE
Version number of generated debian packages violates policy

### ISSUE THREAD

**Issue by pleemann** [ros-infrastructure/ros_buildfarm#484] opened 2017-11-13 13:02 UTC
Not sure if this is the correct repo for this issue, if not please point me to the appropriate location.
 
According to the debian policy (https://www.debian.org/doc/debian-policy/#version ), the format for versions in debian packages should be `[epoch:]upstream_version[-debian_revision]`, with debian_revision not containing hyphens.

The current format of ros packages in the official ppa, which I assume to be generated by the build farm, is e.g. `1.5.2-0xenial-20170725-101547-0800`, which does not follow this naming convention. The upstream_version in this example should be `1.5.2` and debian_increment `0xenial-20170725-101547-0800` (correct?). Because the last hyphen in this string will be used to separate upstream_version from debian_revision, apt and similar programs seem to interpret the upstream_version as `1.5.2-0xenial-20170725-101547` and debian_revision as `0800`. This leads to conflicts when having newer versions of packages, generated by another build system which follows the debian policy.

```
  Installed: (none)
  Candidate: 1.5.2-0xenial-20170725-101547-0800
  Version table:
     1.5.2-0xenial-20170725-101547-0800 500
        500 http://packages.ros.org/ros/ubuntu xenial/main amd64 Packages
     1.5.2-2xenial 500
        500 http://***/ubuntu xenial/main amd64 Packages
     1.5.2-1xenial 500
        500 http://***/ubuntu xenial/main amd64 Packages
```

In the above example (output form `apt-cache policy`), the Install candidate is `1.5.2-0xenial-20170725-101547-0800`, although there is a newer package available `(1.5.2-2xenial)`.

Are you aware of any workaround for this problem? I do not want to resort to apt_preference, it will make things messy and dangerous.

**Comment by dirk-thomas** [comment] 2017-11-13 17:09
This seems to be a duplicate of #460. Unfortunately no consensus has been reached how the current naming should be updated to follow the policy while being backward compatible with existing packages. Maybe you can comment on the pending PR with a suggestion for that.

**Comment by dirk-thomas** [comment] 2017-12-18 16:05
Addressed in future ROS distros (since we can't change the naming scheme in already existing distros) in #460.

**Closed by dirk-thomas** 2017-12-18 16:05 UTC
