### ISSUE TITLE
sourcedeb syncs occasionally fail

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/ros_buildfarm#233] opened 2016-03-07 08:23 UTC
This leaves the sourcedebs empty on the testing repo. 

The problem is that when syncing the sourcedebs we first clear them all, and re-add them all. However if one fails to import the whole import stops leaving the repo empty. 

The error occurs when the orig.tar.gz is inconsistent. This happens when there's a debian increment and bloom recreates the tarball instead of creating a deb diff patch.  

A failed job can be seen here: http://build.ros.org/view/Ksrc_uW/job/Krel_sync-packages-to-testing_wily_amd64/4/console 
```
19:23:50 Creating distributions file /var/repos/ubuntu/testing/conf/distributions
19:23:50 running command ['reprepro', '-v', '-b', '/var/repos/ubuntu/testing', '--noskipold', 'update', 'wily']
19:23:50 Warning: No VerifyRelease line in 'ros-kinetic-wily-source' or any rule it includes via 'From:'.
19:23:50 Release.gpg cannot be checked unless you tell which key to check with.
19:23:50 (To avoid this warning and not check signatures add 'VerifyRelease: blindtrust').
19:23:50 aptmethod got 'file:///var/repos/ubuntu/building/dists/wily/InRelease'
19:23:50 aptmethod got 'file:///var/repos/ubuntu/building/dists/wily/main/source/Sources.gz'
19:23:50 File "pool/main/r/ros-kinetic-catkin/ros-kinetic-catkin_0.7.0.orig.tar.gz" is already registered with different checksums!
19:23:50 md5 expected: 93770d0ded61ab813df8ac629190e740, got: 6a43f7d9ee21dfd5046ab75fd117ff01
19:23:50 sha1 expected: 938f96dd5a5fe6208ca4ddf4c71fd51689693dd5, got: c7242b70b483212ca7604653e460b5e90727e0b7
19:23:50 sha256 expected: 4d16cd79f1c1a847ea0428ce6ea6b7a1f860274a91beba4510e7a75f9baa3f56, got: c87cbb94eacd59e99e32a262fd193d8f3210f1faaa6a855f238d6e50844e719b
19:23:50 size expected: 197515, got: 197531
19:23:50 There have been errors!
```

However once the xenial job removed the other references to orig.tar.gz http://build.ros.org/job/Krel_sync-packages-to-testing_xenial_amd64/3/console

```
19:25:20 removing 'ros-kinetic-catkin' from 'xenial|main|source'...
19:25:20 removing 'ros-kinetic-genmsg' from 'xenial|main|source'...
19:25:20 Exporting indices...
19:25:20 Deleting files no longer referenced...
19:25:20 deleting and forgetting pool/main/r/ros-kinetic-catkin/ros-kinetic-catkin_0.7.0-1xenial.debian.tar.xz
19:25:20 deleting and forgetting pool/main/r/ros-kinetic-catkin/ros-kinetic-catkin_0.7.0-1xenial.dsc
19:25:20 deleting and forgetting pool/main/r/ros-kinetic-catkin/ros-kinetic-catkin_0.7.0.orig.tar.gz
19:25:20 deleting and forgetting pool/main/r/ros-kinetic-genmsg/ros-kinetic-genmsg_0.5.7-0xenial.debian.tar.xz
19:25:20 deleting and forgetting pool/main/r/ros-kinetic-genmsg/ros-kinetic-genmsg_0.5.7-0xenial.dsc
19:25:20 deleting and forgetting pool/main/r/ros-kinetic-genmsg/ros-kinetic-genmsg_0.5.7.orig.tar.gz
19:25:20 running ['reprepro', '-v', '-b', '/var/repos/ubuntu/testing', 'deleteunreferenced']
19:25:20 running command ['reprepro', '-v', '-b', '/var/repos/ubuntu/testing', 'deleteunreferenced']
19:25:20 I have a lock on /var/repos/ubuntu/testing/lock
19:25:20 Creating updates file /var/repos/ubuntu/testing/conf/updates
19:25:20   Name: ros-kinetic-xenial-source
19:25:20   Method: file:///var/repos/ubuntu/building
19:25:20   Suite: xenial
19:25:20   Components: main
19:25:20   Architectures: source
19:25:20   FilterFormula: Package (% ros-kinetic-*)
```

The rerun of the wily sync succeeded.
http://build.ros.org/view/Ksrc_uW/job/Krel_sync-packages-to-testing_wily_amd64/5/console

This is the same underlying issue as https://github.com/ros-infrastructure/ros_buildfarm/pull/140 and https://github.com/ros-infrastructure/reprepro-updater/issues/16 and the best fix would be https://github.com/ros-infrastructure/bloom/issues/150

However for now I'd suggest that we just make sure to rerun the sync when we see this state. It only effects the sourcedebs in the testing repo and sourcedebs from the testing repo are not commonly used.

**Comment by tfoote** [comment] 2016-03-22 06:46
In an edge case, this will not recover if you disable all configurations for a platform. Aka Saucy and the next release is a debinc since the disabled platform will not rerun it's sourcedeb generation and remove the older version. The quick manual solution is to run the sourcedeb for the old job manually(if it's still configured), or to remove the colliding sourcedeb from the repo manually.

**Comment by dirk-thomas** [comment] 2016-08-10 19:20
I will close this ticket since the problem is purely related to `bloom` and nothing else can be done here.

**Closed by dirk-thomas** 2016-08-10 19:20 UTC
Labels: bug
