### ISSUE TITLE
MoveIt builds timeout with 50% chance

### ISSUE THREAD

**Issue by rhaschke** [ros-infrastructure/ros_buildfarm#578] opened 2018-10-22 15:08 UTC
We observe again more frequently build timeouts for MoveIt on the build farm:
* http://build.ros.org/view/Mdev/job/Mdev__moveit__ubuntu_bionic_amd64/
* http://build.ros.org/view/Kdev/job/Kdev__moveit__ubuntu_xenial_amd64/
* http://build.ros.org/view/Idev/job/Idev__moveit__ubuntu_trusty_amd64/

Because the Indigo branch didn't receive many updates for a while, one can see an increase of build time between February and April there. Is this related to #535? Is this issue resolved and everything should work again? Before running the first catkin build, already 45min were spent to setup the docker containers [in this example](http://build.ros.org/view/Mdev/job/Mdev__moveit__ubuntu_bionic_amd64/66/consoleFull#console-section-11).

Shouldn't the docker images be cached in first place? Why they are rebuild every time?

**Comment by tfoote** [comment] 2018-10-22 19:17
#535 was related to apt-get **update** specifically which does not appear to be an issue here. It looks like updates are less than a minute.

We bust the docker cache daily so that we make sure that you have the latest packages to build on top of. We only install exactly what you declare in your manifest dependency so we every job has a custom docker image and can change if you change your dependencies in your code, so it has to be built on demand. The caching works for repeated jobs. For example the latest job 67 only takes 6 minutes to setup due to reusing the cache from job 66 but it still times out.

## Job 67
http://build.ros.org/view/Mdev/job/Mdev__moveit__ubuntu_bionic_amd64/67/consoleFull

The actual build starts between 6 and 7 minutes into the job: http://build.ros.org/view/Mdev/job/Mdev__moveit__ubuntu_bionic_amd64/67/consoleFull#console-section-12

It finishes at 1:03

This is followed by rebuilding the docker image for testing dependencies:
http://build.ros.org/view/Mdev/job/Mdev__moveit__ubuntu_bionic_amd64/67/consoleFull#console-section-13
from 1:03 to 1:08
http://build.ros.org/view/Mdev/job/Mdev__moveit__ubuntu_bionic_amd64/67/consoleFull#console-section-15

At which point it's running the test build and unit test until the 2 hour timeout. 

## Job 66

It's 45 minutes to install the 888 dependent packages before starting the build: http://build.ros.org/view/Mdev/job/Mdev__moveit__ubuntu_bionic_amd64/66/consoleFull#console-section-11

This is ~400MB of downloads unpacking to close to 2GB of content. 
```
00:01:06.488 0 upgraded, 888 newly installed, 0 to remove and 0 not upgraded.
00:01:06.488 Need to get 396 MB of archives.
00:01:06.488 After this operation, 1,919 MB of additional disk space will be used.
```
I'm not sure that there's much more we can do to help with this. In 45 minutes that's only averaging 3 seconds per dependency and with the below notice of there being a 15 minute gap at the end the apt-get install is taking only about 2 seconds per dependency.  (We've cached the download quite well, it was just 22 seconds for that part.) Reproducing locally it takes not much less time.

I do notice an odd gap of close to 15 minutes to invoke apt-get clean
```
00:29:51.280 Updating certificates in /etc/ssl/certs...
00:29:52.494 0 added, 0 removed; done.
00:29:52.494 Running hooks in /etc/ca-certificates/update.d...
00:29:52.523 done.
00:29:52.617 Processing triggers for libgdk-pixbuf2.0-0:amd64 (2.36.11-2) ...
00:29:54.499 Invoking 'apt-get clean'
00:44:51.696 Removing intermediate container bba9aedc8e09
00:44:51.696  ---> 5c873edc6821
00:44:51.696 Step 22/24 : USER buildfarm
00:44:57.343  ---> Running in 3a4f2b682b5d
00:44:58.250 Removing intermediate container 3a4f2b682b5d
00:44:58.250  ---> 72db11d0e0f9
00:44:58.250 Step 23/24 : ENTRYPOINT ["sh", "-c"]
00:44:58.581  ---> Running in 5f1a9c7b4ba9
00:44:59.502 Removing intermediate container 5f1a9c7b4ba9
00:44:59.502  ---> 892dd869a438
00:44:59.502 Step 24/24 : CMD ["PATH=/usr/lib/ccache:$PATH PYTHONPATH=/tmp/ros_buildfarm:$PYTHONPATH python3 -u /tmp/ros_buildfarm/scripts/devel/catkin_make_isolated_and_install.py --rosdistro-name melodic --clean-before --workspace-root /tmp/catkin_workspace"]
```
Though I think that this is more a docker image closeout processing time than apt-get clean taking super long. Docker just doesn't print anything while it's active there.

**Comment by rhaschke** [comment] 2018-10-22 19:35
> I'm not sure that there's much more we can do to help with this.

You are right, building the docker the second time a day, is much faster.
In order to solve the timeout issue for MoveIt, can you increase our timeout please?

**Comment by tfoote** [comment] 2018-10-22 22:13
We don't have the ability to change timeouts per job. And we don't want to increase the overall timeout as the goal of this timeout is to keep jobs from starving the buildfarm of resources when they hang. We give devel and PR jobs priority to give the developers as quick feedback as possible. But as documented above the build itself is taking close to an hour to run.


http://build.ros.org/view/Idev/job/Idev__moveit__ubuntu_trusty_amd64/67/consoleFull#console-section-11

Even on the old builds on indigo there's a large install base. And it takes ~20 minutes. 
```
00:01:51.926 0 upgraded, 806 newly installed, 0 to remove and 1 not upgraded.
00:01:51.926 Need to get 275 MB of archives.
00:01:51.926 After this operation, 1,325 MB of additional disk space will be used.
```
And it would still time out based when it only took 10 minutes to install everything: http://build.ros.org/view/Idev/job/Idev__moveit__ubuntu_trusty_amd64/65/consoleFull#console-section-14


And recently it's still taking ~20 minutes to install indigo w/o caching: 
http://build.ros.org/view/Idev/job/Idev__moveit__ubuntu_trusty_amd64/124/consoleFull#console-section-11

Looking at Kinetic we're up to over 900 dependencies and over 3GB of files to install/extract
http://build.ros.org/view/Kdev/job/Kdev__moveit__ubuntu_xenial_amd64/353/consoleFull#console-section-10
```
00:07:36.723 0 upgraded, 946 newly installed, 0 to remove and 0 not upgraded.
00:07:36.723 Need to get 410 MB of archives.
00:07:36.723 After this operation, 2,153 MB of additional disk space will be used.
```

This is averaging  ~1MB/s to disk.

Caching is great for improving performance when we know things are the same, but we do need to be able to build any package w/o expecting things to have been cached from a previous build. (Such as a cold start on the buildfarm)

Are all of these dependencies necessary? Can some of these components be split and tested separately?

Along the same lines our goal of CI testing is to provide prompt feedback for developers which taking 2+ hours is not really giving prompt feedback.

**Comment by rhaschke** [comment] 2018-10-23 00:04
> We don't have the ability to change timeouts per job. And we don't want to increase the overall timeout

Fully understand this.

> Can some of these components be split and tested separately?

Actually, it was a design decision, suggested by @davetcoleman some? years ago, to merge all components into a huge repo as this facilitates development, which often required parallel changes across packages. So, no chance to test split them.

I guess, you have a script that configures all those jenkins jobs. Couldn't you have (a possibly hard-coded) list of timeout exceptions in this script?

**Comment by davetcoleman** [comment] 2018-10-23 00:45
I worked on timeout issues with MoveIt! a lot several years ago. The solution I came up with was to have Dockerhub create fresh Docker images everytime there was a code change to MoveIt! on Github. This saved our Travis CI tens of minutes (I don't remember how much). This is why we have ``moveit-ci:kinetic`` docker images. A side note, we do have a ``dist-upgrade`` run for our [shadow-fixed Docker](https://github.com/ros-planning/moveit/blob/kinetic-devel/.docker/ci-shadow-fixed/Dockerfile#L26) but we might someday want to remove this.

I've also contacted Travis.org and gotten our build time extended, so we don't have this issue there.

With the ROS farm it has always been a pain, so we've avoided using the PR builds. Can we just turn off the tests for releases?

**Comment by tfoote** [comment] 2018-10-23 21:32
Yeah, I was around for the contralization vs distributed discussion. It's always a trade off.

Due to us doing 1000s of jobs preparing custom heuristics/images for each package is infeasible.

> With the ROS farm it has always been a pain, so we've avoided using the PR builds. Can we just turn off the tests for releases?

You can turn off devel jobs by using `test_commits: false` and pull request testing with `test_pull_requests: false` in the rosdistro entry.

See http://www.ros.org/reps/rep-0143.html#distribution-file for reference.

**Comment by dirk-thomas** [comment] 2018-10-23 21:35
> You can turn off ... pull request testing with test_pull_requests: false in the rosdistro entry.

Pull request testing is "opt in" so you don't have to do anything if you don't want it.

**Comment by davetcoleman** [comment] 2018-10-23 23:11
So if we set ``test_commits: false`` then we will skip the test build and unit tests during the release process? Which should fix our timeout issues for now?

**Comment by dirk-thomas** [comment] 2018-10-23 23:18
`test_commits: false` has nothing to do with releases. When you set the flag no `dev` job is being generated (which are the jobs "triggered" for every commit on the targeted branch). So the jobs you referenced at the top will go away. Basically no more CI testing.

The release jobs don't run the tests of your package and also only operate on packages (not repositories) hence you don't have a problem with your repo containing many packages.

**Comment by davetcoleman** [comment] 2018-10-23 23:40
Ah understood. Ok so we should still turn off ``test_commits``

**Comment by davetcoleman** [comment] 2018-10-23 23:45
https://github.com/ros/rosdistro/pull/19331

**Comment by gavanderhoorn** [comment] 2018-10-24 08:19
Isn't the default for `test_commits` already `false`? REP-143 appears to say that ([here](https://github.com/ros-infrastructure/rep/blame/4a49801c64961b7669eb3bc37c701a9168ee7620/rep-0143.rst#L64)).

**Comment by tfoote** [comment] 2018-10-28 23:49
With the new disk IO all recent builds have passed. I'm going to close this for now.

**Closed by tfoote** 2018-10-28 23:49 UTC
