### ISSUE TITLE
build fails to find package 'apt-src'

### ISSUE THREAD

**Issue by airballking** [ros-infrastructure/ros_buildfarm#287] opened 2016-04-21 06:35 UTC
For one build ```roslisp``` failed to build on the farm. The predecessor and successor builds both succeeded. Builds of the same ```roslisp``` version succeeded for all other build jobs. It seemed like a random error.

I discussed the issue on the release mailing list, and was asked to open an issue here.

Here is the history of builds:
- works: http://build.ros.org/job/Ibin_uT32__roslisp__ubuntu_trusty_i386__binary/3/
- fails: http://build.ros.org/job/Ibin_uT32__roslisp__ubuntu_trusty_i386__binary/4/
- works: http://build.ros.org/job/Ibin_uT32__roslisp__ubuntu_trusty_i386__binary/5/

EDIT: In case the above pages get overwritten with the next builds, the specific error was: The package ```apt-src``` could not be find even though an earlier ```apt-get update``` finished successfully. That happened in step 11.2 of the build.

Here is the command output from the farm: 
[command-output-buildfarm-fail-roslisp.zip](https://github.com/ros-infrastructure/ros_buildfarm/files/229321/command-output-buildfarm-fail-roslisp.zip)

**Comment by dirk-thomas** [comment] 2016-04-26 18:38
At the point where the build farm invoked `apt-src` it has "dropped" its root privileges and can't invoke apt-get update anymore`. The problem is similar as https://github.com/ros-infrastructure/ros_buildfarm/issues/170#issuecomment-214824422 and as far as I can tell a problem in `apt-get` as it pretended to have finished successfully.

I will close this as "wontfix" since I don't see a way to address the problem. Sorry.

Please feel free to continue commenting here.

**Closed by dirk-thomas** 2016-04-26 18:38 UTC
Labels: wontfix

**Comment by dirk-thomas** [comment] 2016-04-26 18:44
Duplicate of #248.
