### ISSUE TITLE
release new version targeting hosts based on Xenial

### ISSUE THREAD

**Issue by jonazpiazu** [ros-infrastructure/ros_buildfarm#507] opened 2018-01-29 15:18 UTC
According to the [job generation documentation](https://github.com/ros-infrastructure/ros_buildfarm/blob/master/doc/environment.rst#virtualenv) , the ros_buildfarm is installed using `pip`. 

However the package is not updated. For example, for the `import_upstream` job, the path to the configuration file wrongly points to `/home/jenkins-slave/reprepro_config/ros_bootstrap.yaml`

https://github.com/ros-infrastructure/ros_buildfarm/blob/master/ros_buildfarm/templates/release/import_upstream_job.xml.em#L29

**Comment by dirk-thomas** [comment] 2018-01-29 16:49
When installing this package via `pip` using the package name the latest release is being installed. Currently that is version 1.4.1 from August 30th 2017. That version was tagged when Ubuntu Trusty was the targeted host platform. The line you referenced has been changed in the meantime to target Xenial as the host system.

Since there are several regressions (ros-infrastructure/buildfarm_deployment#165, ros-infrastructure/buildfarm_deployment#176, the `import_upstream` job is significantly slower) still pending related to the migration to Xenial there hasn't been a new version of `ros_buildfarm` yet. If you still want to use the latest deployment using Xenial you need to install the latest code from the master branch of this repo rather than the latest release (e.g. but invoking `pip` with the URL of this repo).

**Comment by jonazpiazu** [comment] 2018-01-29 18:32
I see. Then I suggest to update the install instructions, as I would assume that they currently apply to the Xenial version.

**Comment by dirk-thomas** [comment] 2018-01-29 18:34
> I would assume that they currently apply to the Xenial version.

The current instructions start with:

> The following commands can be used on Ubuntu Trusty::

**Comment by jonazpiazu** [comment] 2018-01-29 18:45
My understanding from [this](https://discourse.ros.org/t/ros-buildfarm-october-2017-guide-to-new-changes/2840) and [this](https://discourse.ros.org/t/status-of-xenial-migration/3330/9) posts was that the *official* version for the buildfarm is Xenial. But maybe I run too much.

**Comment by dirk-thomas** [comment] 2018-01-29 18:48
That is correct. Yet there is no new release of `ros_buildfarm` at this point for the reasons mentioned above. Yes, that is not optimal but that is how it is atm.

**Comment by cclauss** [comment] 2018-08-29 13:57
Would it be worthwhile to take another look at this one?
* The two issues sited were closed in March 2018.
* Trusty will EOL in April 2019
* Python 3.7 is current but we are advocating 3.4.

**Comment by dirk-thomas** [comment] 2018-08-29 14:17
Version 2.0.0 of this package targeting Xenial was already released in April.

> Python 3.7 is current but we are advocating 3.4.

The buildfarm is not advocating for any specific Python version. I simply uses the default version available on the targeted platform.

**Closed by dirk-thomas** 2018-08-29 14:17 UTC
