### ISSUE TITLE
Release ros_buildfarm

### ISSUE THREAD

**Issue by mikaelarguedas** [ros-infrastructure/ros_buildfarm#394] opened 2017-03-07 06:40 UTC
`python-ros-buildfarm` needs to be released for the prerelease tests to run for newer ubuntu distros (specifically [this commit](https://github.com/ros-infrastructure/ros_buildfarm/commit/db4e7faa8393056dbf59ca7f49c683e2d1f8db96) is needed)

**Comment by dirk-thomas** [comment] 2017-03-07 06:57
I will release a new minor once the Lunar buildfarm is working "stable".

Especially the regression from https://github.com/ros-infrastructure/ros_buildfarm/pull/374#issuecomment-284485650 needs to be resolved before.

**Comment by dirk-thomas** [comment] 2017-03-11 02:29
Still another regression to address before a release, see https://github.com/ros-infrastructure/ros_buildfarm/pull/398/

**Comment by dirk-thomas** [comment] 2017-03-13 16:23
Still waiting for follow up work from #398 for `saucy` and `trusty`.

**Comment by dirk-thomas** [comment] 2017-03-14 22:04
There are two pending PRs which can probably both be merged soon.

@mikaelarguedas Let me know once the next debinc release worked well and I can go ahead with a release.

**Comment by tfoote** [comment] 2017-03-15 08:52
With the new version of bloom opencv3 sourcedebs built successfully: http://build.ros.org:8080/job/Lsrc_uZ__opencv3__ubuntu_zesty__source/7/console where it was failing without the patch.

Also http://build.ros.org:8080/job/Lsrc_uY__opencv3__ubuntu_yakkety__source/ and http://build.ros.org:8080/job/Lsrc_dS__opencv3__debian_stretch__source/ recovered. The binary jobs are failing due to not having the new rosdep rule: https://github.com/ros/rosdistro/pull/14170 pinged vincent here: https://github.com/ros/rosdistro/pull/14175

Kinetic is rolling again: 
http://build.ros.org:8080/job/Ksrc_dJ__opencv3__debian_jessie__source/


And jade back to trusty: http://build.ros.org:8080/job/Jsrc_uT__opencv3__ubuntu_trusty__source/

**Comment by dirk-thomas** [comment] 2017-03-15 23:01
And waiting for the result of the discussion in #392 before making the release...

**Comment by dirk-thomas** [comment] 2017-03-16 18:31
Based on the conversation I created #405.

**Comment by dirk-thomas** [comment] 2017-03-16 23:44
Version [1.3.0](https://github.com/ros-infrastructure/ros_buildfarm/releases/tag/1.3.0) :ship:

**Comment by mikaelarguedas** [comment] 2017-03-16 23:44
:+1: :tada:

**Closed by dirk-thomas** 2017-03-16 23:44 UTC
