### ISSUE TITLE
[docker-based prerelease] Wrong path to reprodution upon failure

### ISSUE THREAD

**Issue by 130s** [ros-infrastructure/ros_buildfarm#283] opened 2016-04-13 20:07 UTC
Although this may not be the right repo to report...

I get a message like this when docker-based prerelease fails:

```
$ generate_prerelease_script.py   https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml   indigo default ubuntu trusty amd64   moveit_msgs   --level 0   --output-dir ./
$ ./prerelease.sh 
:
Reproduce this error by running:
==> cd /tmp/catkin_workspace/build_isolated/moveit_ros_planning && /tmp/catkin_workspace/install_isolated/env.sh make -j1
```

But `cd` fails to find the path. The right path should start with `/tmp/prerelease_job/catkin_workspace` I think.

The [code that prints the message is in ros/catkin](https://github.com/ros/catkin/blob/c76db04d75c7d67cfaf9d5744faee8722cd87b7f/python/catkin/builder.py#L978). I just can't think of how to fix this.

**Comment by 130s** [comment] 2016-04-14 21:37
Actually filling what I thought missing directory still does not work.

- OLD: cd /tmp/catkin_workspace/build_isolated/moveit_ros_planning && /tmp/catkin_workspace/install_isolated/env.sh make -j1
- PROPOSED: cd /tmp/prerelease_job/catkin_workspace/build_isolated/moveit_ros_planning && /tmp/prerelease_job/catkin_workspace/install_isolated/env.sh make -j1

PROPOSED command resuls in:

```
CMake Error: The source directory "/tmp/catkin_workspace/src/moveit_ros/planning" does not exist.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** [cmake_check_build_system] Error 1
```

**Comment by 130s** [comment] 2016-05-17 21:02
**UPDATE**: the output [above](https://github.com/ros-infrastructure/ros_buildfarm/issues/283#issuecomment-210159885) is still using the "OLD" path by mistake. I'll have to rerun and get the output using "PROPOSED" command.

**Comment by dirk-thomas** [comment] 2016-05-17 22:06
If your base path outside and inside Docker is different the printed path does not match. To fix this the Docker container needs to use the same base path as outside.

**Comment by dirk-thomas** [comment] 2016-05-18 19:36
I would propose to close this since the command conceptionally can't be invoked outside of Docker.

**Comment by 130s** [comment] 2016-05-18 23:49
Trying to understand,

> If your base path outside and inside Docker is different the printed path does not match. To fix this the Docker container needs to use the same base path as outside.

Does this mean that the user of prerelease scripts should `cd /tmp/prerelease_job` before running `prerelease.sh` to avoid the different path issue I mentioned in this ticket?

(I'm not sure what you mean by `your base path outside and inside Docker`.)

**Comment by 130s** [comment] 2016-05-18 23:54
(Hit the send button prematurely)

Trying to understand,

> If your base path outside and inside Docker is different the printed path does not match. To fix this the Docker container needs to use the same base path as outside.

Does this mean that the user of prerelease scripts should `cd /tmp/prerelease_job` before running `prerelease.sh` to avoid the different path issue I mentioned in this ticket? If so that's actually instructed by prerelease website; full command I get is:

 ```
mkdir -p /tmp/prerelease_job; cd /tmp/prerelease_job; sudo -E generate_prerelease_script.py https://raw.githubusercontent.com/ros-infrastructure/ros_buildfarm_config/production/index.yaml jade default ubuntu trusty amd64 moveit_msgs --level 0 --output-dir ./
```

I'm not sure what you mean by `your base path outside and inside Docker`.
Thanks!

**Comment by dirk-thomas** [comment] 2016-05-18 23:55
The message:

> Reproduce this error by running:
==> cd /tmp/catkin_workspace/build_isolated/moveit_ros_planning && /tmp/catkin_workspace/install_isolated/env.sh make -j1

is coming from a programming running inside of Docker. That program doesn't know that it is being run in Docker. It simply says how it can be reproduced in the "current" context.

After the prerelease script returned you can't simply run that command to reproduce the problem. You would need to get into the same Docker environment.

**Closed** 2016-08-10 19:50 UTC
